feat: add Units, viewBox of pattern
react-native-oh-library/react-native-harmony-svg pull request #84
Opened 2024-05-13 14:11 UTC by shinyxhh

2024-05-13 14:32 UTC, ezhoureal requested changes

2024-05-13 14:32 UTC, ezhoureal commented on tester/harmony/svg/src/main/cpp/utils/SvgAttributesParser.h
> +};
为什么要套一层，同时有SvgPatternAttribute 和Pattern

2024-05-13 14:32 UTC, ezhoureal commented on tester/harmony/svg/src/main/cpp/SvgGraphic.cpp
> +
为什么要新写一个转换函数，不能用converToPx吗

2024-05-13 14:32 UTC, ezhoureal commented on tester/harmony/svg/src/main/cpp/properties/SvgPaintState.h
> +    std::optional<Pattern> pattern_;
为什么已经用optional了还要加个flag

2024-05-13 14:35 UTC, shinyxhh commented on tester/harmony/svg/src/main/cpp/SvgGraphic.cpp
> +
attr 和 value是两个不同的值

2024-05-13 14:39 UTC, shinyxhh commented on tester/harmony/svg/src/main/cpp/utils/SvgAttributesParser.h
> +};
在实现逻辑里需要判断是否是pattern这个类的组件，所以封装了一层

2024-05-13 14:40 UTC, shinyxhh commented on tester/harmony/svg/src/main/cpp/properties/SvgPaintState.h
> +    std::optional<Pattern> pattern_;
参考的其他组件的类似实现

2024-05-14 06:07 UTC, ezhoureal commented on tester/harmony/svg/src/main/cpp/SvgGraphic.cpp
> +
看起来跟这个函数是一样的
![image](https://github.com/react-native-oh-library/react-native-harmony-svg/assets/30425920/c3ce7d2b-b702-452e-b05c-61ae18754ef3)

2024-05-14 06:08 UTC, ezhoureal requested changes

2024-05-14 06:08 UTC, ezhoureal commented on tester/harmony/svg/src/main/cpp/properties/SvgPaintState.h
> +    std::optional<Pattern> pattern_;
gradient实现也有问题，先把你这个改了吧

2024-05-14 06:10 UTC, ezhoureal commented on tester/harmony/svg/src/main/cpp/utils/SvgAttributesParser.h
> +};
不理解，这怎么会用来判断

2024-05-14 10:00 UTC, ezhoureal requested changes

2024-05-14 10:00 UTC, ezhoureal commented on tester/harmony/svg/src/main/cpp/SvgNode.cpp
> +    }
这样pattern属性对象对象会多复制了一次，还有名字改成GetPatternAttr，pattern节点和pattern属性区分一下

2024-05-14 13:12 UTC, ezhoureal approved these changes

2024-05-14 13:26 UTC, merged